# [wiki](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#include-a-single-file-from-a-url)
# --------------
# File example
# --------------
# [".oh-my-zsh"]
#     type = "archive"
#     url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
# --------------
# Git Repo example
# --------------
# [".vim/pack/alker0/chezmoi.vim"]
#     type = "git-repo"
#     url = "https://github.com/alker0/chezmoi.vim.git"
#     refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
